# Generated by Django 4.2.25 on 2025-11-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0002_statuses_alter_proj_title_folders_cases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuses',
            new_name='CaseStoreStatuses',
        ),
    ]
