# Generated by Django 4.2.25 on 2025-11-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0003_rename_statuses_casestorestatuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proj',
            name='text',
        ),
    ]
