# Generated by Django 4.2.25 on 2025-11-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0004_remove_proj_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proj',
            old_name='published_date',
            new_name='last_update_date',
        ),
    ]
