# Generated by Django 4.2.25 on 2025-11-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0005_rename_published_date_proj_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj',
            name='personel',
            field=models.CharField(default='untitled_author', max_length=100),
        ),
    ]
