# Generated by Django 4.2.25 on 2025-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0006_proj_personel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj',
            name='personel',
            field=models.CharField(default='untitled_author', max_length=1000),
        ),
    ]
