# Generated by Django 4.2.25 on 2025-11-03 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0007_alter_proj_personel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj',
            name='last_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
