# Generated by Django 4.2.25 on 2025-11-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0008_alter_proj_last_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='level',
        ),
    ]
