# Generated by Django 4.2.25 on 2025-11-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0009_remove_cases_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='norma.folders', verbose_name='Родительская папка'),
        ),
    ]
