# Generated by Django 4.2.25 on 2025-11-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0010_folders_parent_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='folder_id',
            new_name='folder',
        ),
    ]
