# Generated by Django 4.2.25 on 2025-11-06 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('norma', '0011_rename_folder_id_cases_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершен')], default='В процессе', max_length=20)),
                ('assignees', models.CharField(default='default tester', max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cases', models.PositiveIntegerField(default=0, verbose_name='Всего кейсов')),
                ('passed_cases', models.PositiveIntegerField(default=0, verbose_name='Пройдено')),
                ('failed_cases', models.PositiveIntegerField(default=0, verbose_name='Провалено')),
                ('unknown_cases', models.PositiveIntegerField(default=0, verbose_name='Неизвестных')),
                ('skipped_cases', models.PositiveIntegerField(default=0, verbose_name='Пропущенных')),
                ('correction_needed_cases', models.PositiveIntegerField(default=0, verbose_name='Требует правки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.proj')),
            ],
        ),
        migrations.RemoveField(
            model_name='cases',
            name='status',
        ),
        migrations.RemoveField(
            model_name='casestorestatuses',
            name='name',
        ),
        migrations.CreateModel(
            name='TestRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'успешный'), ('failed', 'проваленный'), ('unknown', 'неизвестный'), ('skipped', 'пропущенный'), ('correction_needed', 'кейс требует правки')], default='not_run', max_length=20, verbose_name='Статус выполнения')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='test_run_attachments/', verbose_name='Приложение')),
                ('execution_time', models.PositiveIntegerField(default=0, verbose_name='Время выполнения (минуты)')),
                ('defect_url', models.URLField(blank=True, verbose_name='Ссылка на дефект')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_results', to='norma.cases', verbose_name='Тест-кейс')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='norma.launches', verbose_name='Запуск тестов')),
            ],
        ),
    ]
