# Generated by Django 4.2.25 on 2025-11-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0012_launches_remove_cases_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseStoreStatuses',
        ),
    ]
