# Generated by Django 4.2.25 on 2025-11-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0013_delete_casestorestatuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrunresult',
            name='test_run',
        ),
        migrations.CreateModel(
            name='LaunchedCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.launches')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.cases')),
            ],
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_results', to='norma.launchedcases', verbose_name='Тест-кейс'),
        ),
    ]
