# Generated by Django 4.2.25 on 2025-11-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0014_remove_testrunresult_test_run_launchedcases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrunresult',
            name='test_case',
        ),
        migrations.AddField(
            model_name='testrunresult',
            name='launch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='norma.launches'),
        ),
        migrations.AddField(
            model_name='testrunresult',
            name='testCase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='norma.cases'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrunresult',
            name='title',
            field=models.CharField(default='DefaultResult', max_length=100),
        ),
        migrations.DeleteModel(
            name='LaunchedCases',
        ),
    ]
