# Generated by Django 4.2.25 on 2025-11-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0015_remove_testrunresult_test_case_testrunresult_launch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrunresult',
            name='title',
        ),
    ]
