# Generated by Django 4.2.25 on 2025-11-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0016_remove_testrunresult_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('on_review', 'На ревью'), ('actual', 'Актуальный'), ('correction_needed', 'Требует доработки')], default='Черновик', max_length=20),
        ),
    ]
