# Generated by Django 4.2.25 on 2025-11-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0017_cases_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='folder',
        ),
        migrations.AddField(
            model_name='cases',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='case_project', to='norma.proj'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Folders',
        ),
    ]
