# Generated by Django 4.2.26 on 2025-11-12 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('norma', '0017_cases_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('description', models.TextField(blank=True, verbose_name='Описание папки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень вложенности')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Автор папки')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='norma.folder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Уровень вложенности')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок тест-кейса')),
                ('description', models.TextField(blank=True, verbose_name='Описание тест-кейса')),
                ('preconditions', models.TextField(blank=True, verbose_name='Предусловия')),
                ('steps', models.JSONField(default=list, verbose_name='Шаги тестирования')),
                ('expected_result', models.TextField(verbose_name='Ожидаемый результат')),
                ('actual_result', models.TextField(blank=True, verbose_name='Фактический результат')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('archived', 'Архивный')], default='draft', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень вложенности')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to=settings.AUTH_USER_MODEL, verbose_name='Автор тест-кейса')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='norma.folder', verbose_name='Папка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='norma.project', verbose_name='Проект')),
                ('related_cases', models.ManyToManyField(blank=True, to='norma.testcase', verbose_name='Связанные тест-кейсы')),
            ],
            options={
                'verbose_name': 'Тест-кейс',
                'verbose_name_plural': 'Тест-кейсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('action', models.TextField(verbose_name='Действие')),
                ('expected_result', models.TextField(verbose_name='Ожидаемый результат')),
                ('actual_result', models.TextField(blank=True, verbose_name='Фактический результат')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_steps', to='norma.testcase', verbose_name='Тест-кейс')),
            ],
            options={
                'verbose_name': 'Шаг тест-кейса',
                'verbose_name_plural': 'Шаги тест-кейса',
                'ordering': ['step_number'],
                'unique_together': {('test_case', 'step_number')},
            },
        ),
        migrations.RemoveField(
            model_name='folders',
            name='parent_folder',
        ),
        migrations.RemoveField(
            model_name='folders',
            name='project',
        ),
        migrations.RemoveField(
            model_name='launches',
            name='author',
        ),
        migrations.RemoveField(
            model_name='launches',
            name='project',
        ),
        migrations.RemoveField(
            model_name='proj',
            name='author',
        ),
        migrations.RemoveField(
            model_name='testrunresult',
            name='executed_by',
        ),
        migrations.RemoveField(
            model_name='testrunresult',
            name='launch',
        ),
        migrations.RemoveField(
            model_name='testrunresult',
            name='testCase',
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.DeleteModel(
            name='Folders',
        ),
        migrations.DeleteModel(
            name='Launches',
        ),
        migrations.DeleteModel(
            name='Proj',
        ),
        migrations.DeleteModel(
            name='TestRunResult',
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='norma.project', verbose_name='Проект'),
        ),
    ]
