# Generated by Django 4.2.25 on 2025-11-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0018_remove_cases_folder_cases_project_delete_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunresult',
            name='title',
            field=models.CharField(default='Результат', max_length=100),
        ),
    ]
