# Generated by Django 4.2.25 on 2025-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0019_testrunresult_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrunresult',
            name='status',
            field=models.CharField(choices=[('passed', 'успешный'), ('failed', 'проваленный'), ('unknown', 'неизвестный'), ('skipped', 'пропущенный'), ('correction_needed', 'кейс требует правки'), ('in_progress', 'в процессе')], default='not_run', max_length=20, verbose_name='Статус выполнения'),
        ),
    ]
