# Generated by Django 4.2.25 on 2025-11-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0020_alter_testrunresult_status'),
    ]

    operations = [
        # Удаляем все существующие TestRunResult записи
        migrations.RunSQL(
            sql="DELETE FROM norma_testrunresult;",
            reverse_sql="",  # Нет нужды восстанавливать удалённые данные при откате
        ),
        migrations.RemoveField(
            model_name='testrunresult',
            name='testCase',
        ),
        migrations.AddField(
            model_name='testrunresult',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='norma.cases'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='launch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='norma.launches'),
        ),
    ]
