# Generated by Django 4.2.25 on 2025-11-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0022_alter_testrunresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launches',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершен')], default='in_progress', max_length=20),
        ),
    ]
