# Generated by Django 4.2.25 on 2025-11-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0023_alter_launches_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('on_review', 'На ревью'), ('actual', 'Актуальный'), ('correction_needed', 'Требует доработки')], default='draft', max_length=20),
        ),
    ]
